<a href="https://colab.research.google.com/github/Lasturka/etn-AI/blob/main/_3_Etn_milk_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Discriminant Analysis (LDA)

## Importing the dataset

*   Pandas library to load csv
*   Independent variables (X): all rows incl. first header | columns from the third till the end
*   Dependent variable (y): second column
*   First column irrelevant

In [ ]:
import pandas as pd
dataset = pd.read_csv('milk.csv')
X = dataset.iloc[:, 2:].values
y = dataset.iloc[:, 1].values

## Splitting the dataset into the Training set and Test set

*   keeping default 75 % train set, 25 % test set
*   random_state for consistent results



In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

## Feature Scaling

*   Use standardization to resize values (mean -> 0, std. dev. = 1) for enhance model performance
*   test set uses values computed on train set



In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
import tensorflow as tf
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
ann.compile(optimizer = 'adam', loss = tf.keras.losses.categorical_crossentropy, metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
11/11 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.1039
Epoch 2/100
11/11 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.1039
Epoch 3/100
11/11 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.1039
Epoch 4/100
11/11 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.1039
Epoch 5/100
11/11 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.1039
Epoch 6/100
11/11 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.1039
Epoch 7/100
11/11 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.1039
Epoch 8/100
11/11 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.1039
Epoch 9/100
11/11 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.1039
Epoch 10/100
11/11 [==============================] - 0s 4ms/step - loss:

## Applying PCA

*   classification algorithm to reduce dimensionality
*   component axes that maximize the variance

In [ ]:
from sklearn.decomposition import PCA
pca = PCA()
X_trainPCA = pca.fit_transform(X_train)
X_testPCA = pca.transform(X_test)

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_trainPCA, y_train, batch_size = 32, epochs = 100)

## Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifierPCA = LogisticRegression(random_state = 0, max_iter=10000)
classifierPCA.fit(X_trainPCA, y_train)

LogisticRegression(max_iter=10000, random_state=0)

## Making the Confusion Matrix and compute accuracy




In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_predPCA = classifierPCA.predict(X_testPCA)
cm = confusion_matrix(y_test, y_predPCA)
print(cm)
print("Accuracy score: {:.2f} %".format(accuracy_score(y_test, y_predPCA)*100))

from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifierPCA, X = X_trainPCA, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

[[15  0  0  0  0  0  0  0  0]
 [ 0 13  0  0  0  0  0  0  0]
 [ 0  0 13  0  0  0  0  0  0]
 [ 0  0  0 13  0  1  0  0  0]
 [ 0  0  0  0 14  0  0  0  0]
 [ 0  0  0  0  0  9  0  0  0]
 [ 0  0  0  0  0  0 10  0  0]
 [ 0  0  0  0  0  0  0 14  0]
 [ 0  0  0  0  0  0  0  1 10]]
Accuracy score: 98.23 %
Accuracy: 99.41 %
Standard Deviation: 1.18 %
